version: '3'
services:
  nginx:
   container_name: some-nginx
   image: nginx:latest
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - demo

  demo:
    container_name: some-demo
    restart: always
    build: ./demo
    working_dir: /demo
    volumes:
      - ./demo:/demo
    expose:
      - "8080"
    command: ./gradlew bootrun
