version: '3'
services:
  nginx:
   container_name: nginx-server
   image: nginx:latest
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - helloworld

  helloworld:
    container_name: helloworld-service
    restart: always
    build: ./helloworld
    working_dir: /helloworld
    volumes:
      - ./helloworld:/helloworld
    expose:
      - "8080"
    command: ./gradlew bootrun
